### ISSUE TITLE
Worldguard not working using FAWE

### ISSUE THREAD

**Issue by iKipper** [darbyjack/Guilds-Plugin#103]
Trying to use FAWE worldguard version https://empcraft.com/fawe/download/ with Guilds and it throws this error, any way of fixing so we can run both plugins? We dont want to have to remove guilds....
[16:47:08] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Guilds v3.3-RELEASE
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:298) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:457) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1244) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-a1f2566-a4c555b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitAdapter.asBlockVector(Lorg/bukkit/Location;)Lcom/sk89q/worldedit/math/BlockVector3;
	at me.glaremasters.libs.worldguardwrapper.implementation.v7.WorldGuardImplementation.lambda$getApplicableRegions$1(WorldGuardImplementation.java:50) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_181]
	at me.glaremasters.libs.worldguardwrapper.implementation.v7.WorldGuardImplementation.getApplicableRegions(WorldGuardImplementation.java:50) ~[?:?]
	at me.glaremasters.libs.worldguardwrapper.implementation.v7.WorldGuardImplementation.getRegions(WorldGuardImplementation.java:139) ~[?:?]
	at me.glaremasters.libs.worldguardwrapper.WorldGuardWrapper.getRegions(WorldGuardWrapper.java:25) ~[?:?]
	at me.glaremasters.guilds.listeners.WorldGuard.onInteract(WorldGuard.java:69) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot.jar:git-Spigot-a1f2566-a4c555b]
	... 17 more

**Comment by HauserGrim** [comment]
fawe wg have otdated api, update wafe & fawe wg to normal we & wg.

**Comment by darbyjack** [comment]
The next update should have an updated version of the wrapper.
