### ISSUE TITLE
Guild create error

### ISSUE THREAD

**Issue by Jessy142** [darbyjack/Guilds-Plugin#105]
Running Guilds 3.3 Release
Running Spigot 1.13.2

Trying to create a guild, get the following error in console. (Guild doesn't create)

> [11:32:05 INFO]: Vlegel issued server command: /guild create TestGuild
[11:32:07 INFO]: Vlegel issued server command: /guilds confirm
[11:32:07 ERROR]: [ACF] Exception in command: guild confirm
[11:32:07 ERROR]: [ACF] java.lang.reflect.InvocationTargetException
[11:32:07 ERROR]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:32:07 ERROR]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[11:32:07 ERROR]: [ACF]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[11:32:07 ERROR]: [ACF]         at java.lang.reflect.Method.invoke(Unknown Source)
[11:32:07 ERROR]: [ACF]         at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:147)
[11:32:07 ERROR]: [ACF]         at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:650)
[11:32:07 ERROR]: [ACF]         at co.aikar.commands.BaseCommand.execute(BaseCommand.java:493)
[11:32:07 ERROR]: [ACF]         at co.aikar.commands.RootCommand.execute(RootCommand.java:67)
[11:32:07 ERROR]: [ACF]         at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:62)
[11:32:07 ERROR]: [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:32:07 ERROR]: [ACF]         at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
[11:32:07 ERROR]: [ACF]         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[11:32:07 ERROR]: [ACF]         at java.util.concurrent.FutureTask.run(Unknown Source)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[11:32:07 ERROR]: [ACF]         at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[11:32:07 ERROR]: [ACF]         at java.lang.Thread.run(Unknown Source)
[11:32:07 ERROR]: [ACF] Caused by: java.lang.NullPointerException
[11:32:07 ERROR]: [ACF]         at me.glaremasters.guilds.commands.CommandGuilds$1.accept(CommandGuilds.java:126)
[11:32:07 ERROR]: [ACF]         at me.glaremasters.guilds.commands.CommandGuilds.onConfirm(CommandGuilds.java:168)
[11:32:07 ERROR]: [ACF]         ... 24 more

**Comment by HauserGrim** [comment]
+1
Server ver: latest paper 1.13.2
Plugins: latest vault and guilds

**Comment by HauserGrim** [comment]
When I put essentialsx error disappeared.

**Comment by Jessy142** [comment]
> When I put essentialsx error disappeared.

Going to try this, thanks

**Comment by darbyjack** [comment]
Known error, should be fixed.
