### ISSUE TITLE
NPE whenever someone chats.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#14]
Guilds v1.6.6-release.

NPE occurs whenever someone chats publicly in-game.

```
[04:46:20] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Guilds v1.6.6-RELEASE
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.12.jar:git-Paper-1145]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) [patched_1.12.jar:git-Paper-1145]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1339) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1254) [patched_1.12.jar:git-Paper-1145]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.12.jar:git-Paper-1145]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at me.bramhaag.guilds.listeners.ChatListener.onPlayerChat(ChatListener.java:19) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor122.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.jar:git-Paper-1145]
	... 12 more
```

**Comment by mibby** [comment]
Closing as it is no longer an issue with the latest version.
