### ISSUE TITLE
IOException when loading Guilds without default files existing.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#24]
```
[03:14:50] [Server thread/INFO]: [Guilds] Enabling Guilds v1.7.1-RELEASE
[03:14:50] [Server thread/WARN]: java.io.IOException: The system cannot find the path specified
[03:14:50] [Server thread/WARN]: 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[03:14:50] [Server thread/WARN]: 	at java.io.File.createNewFile(Unknown Source)
[03:14:50] [Server thread/WARN]: 	at me.glaremasters.guilds.database.databases.json.Json.initialize(Json.java:49)
[03:14:50] [Server thread/WARN]: 	at me.glaremasters.guilds.Main.setDatabaseType(Main.java:304)
[03:14:50] [Server thread/WARN]: 	at me.glaremasters.guilds.Main.onEnable(Main.java:97)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[03:14:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[03:14:50] [Server thread/WARN]: java.io.IOException: The system cannot find the path specified
[03:14:50] [Server thread/WARN]: 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[03:14:50] [Server thread/WARN]: 	at java.io.File.createNewFile(Unknown Source)
[03:14:50] [Server thread/WARN]: 	at me.glaremasters.guilds.database.databases.json.Json.initialize(Json.java:60)
[03:14:50] [Server thread/WARN]: 	at me.glaremasters.guilds.Main.setDatabaseType(Main.java:304)
[03:14:50] [Server thread/WARN]: 	at me.glaremasters.guilds.Main.onEnable(Main.java:97)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380)
[03:14:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290)
[03:14:50] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[03:14:50] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: java.io.FileNotFoundException: plugins\Guilds\data\guilds.json (The system cannot find the path specified)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.io.FileReader.<init>(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at me.glaremasters.guilds.database.databases.json.Json.lambda$getGuilds$5(Json.java:102)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at co.aikar.taskchain.TaskChainTasks$FirstTask.run(TaskChainTasks.java:55)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at co.aikar.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1078)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: java.io.FileNotFoundException: plugins\Guilds\data\leaderboards.json (The system cannot find the path specified)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.io.FileInputStream.open(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.io.FileInputStream.<init>(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.io.FileReader.<init>(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at me.glaremasters.guilds.database.databases.json.Json.lambda$getLeaderboards$14(Json.java:160)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at co.aikar.taskchain.TaskChainTasks$FirstTask.run(TaskChainTasks.java:55)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at co.aikar.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1078)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[03:14:50] [TaskChainAsyncQueue Thread 1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[03:14:50] [Server thread/INFO]: [Guilds] Configuration file reloaded!
```

**Comment by darbyjack** [comment]
Somewhat fixed.
