### ISSUE TITLE
CommandException on '/guild info' command.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#35]
Guilds version 1.7.7-RELEASE

```/guild info``` command does not function. Only outputs an internal error occurred in chat with this exception in console.
```
[02:12:42] [Server thread/INFO]: player issued server command: /guild info
[02:12:42] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'guild' in plugin Guilds v1.7.7-RELEASE
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.1.jar:git-Paper-1172]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.1.jar:git-Paper-1172]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425) ~[patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230) ~[patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1172]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
	at java.util.ArrayList.set(ArrayList.java:444) ~[?:1.8.0_144]
	at me.glaremasters.guilds.commands.CommandInfo.execute(CommandInfo.java:101) ~[?:?]
	at me.glaremasters.guilds.commands.base.CommandHandler.onCommand(CommandHandler.java:81) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1172]
	... 15 more
```

**Comment by darbyjack** [comment]
Looking into / fixed.
