### ISSUE TITLE
CommandException: Unhandled exception executing command

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#46]
Guilds dev 40

```
[16:58:20] [Server thread/INFO]: player issued server command: /guild admin info Aurora
[16:58:20] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'guild' in plugin Guilds v1.8.2-BETA
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.1.jar:git-Paper-1178]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.1.jar:git-Paper-1178]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425) ~[patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230) ~[patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1178]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1178]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1178]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(Unknown Source) ~[?:1.8.0_144]
	at me.glaremasters.guilds.message.Message.replace(Message.java:85) ~[?:?]
	at me.glaremasters.guilds.commands.CommandAdmin.execute(CommandAdmin.java:116) ~[?:?]
	at me.glaremasters.guilds.commands.base.CommandHandler.onCommand(CommandHandler.java:78) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1178]
	... 15 more
```

```
  "Aurora": {
    "prefix": "AR",
    "members": [
      {
        "uuid": "72c34e55-b89a-49b4-9db0-0a1c8a1a0675",
        "role": 0
      },
      {
        "uuid": "8a6e81b5-22f2-4de4-a6c2-19761a2132f9",
        "role": 1
      },
      {
        "uuid": "cbbb484d-30b6-4f4b-9644-bc5cf37d8317",
        "role": 3
      }
    ],
    "allies": [
      "VilleDuFleur"
    ],
    "invitedMembers": [],
    "pendingAllies": []
  },
```

**Comment by darbyjack** [comment]
I was able to produce this just fine. https://i.glaremasters.me/i/02ombzq.png

**Comment by mibby** [comment]
@darbyjack Add the guild to your json file manually and try to get the info of it in-game. NPE probably occurs because it can't find the player names that belong to the UUID if it is missing from the server uuid cache.
