### ISSUE TITLE
NullPointerException getSkullsPage on guild list.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#48]
Guilds v1.8.4-BETA dev 60

NPE occurs when typing ```/guilds list```. Related to https://github.com/darbyjack/Guilds-Plugin/issues/46 where NPE occurs when it can't find a player by their UUID?

```
[20:23:46] [Server thread/INFO]: mibby issued server command: /guilds list
[20:23:46] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'town' in plugin Guilds v1.8.4-BETA
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.1.jar:git-Paper-1190]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.1.jar:git-Paper-1190]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1425) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1230) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1190]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1190]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1190]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at java.lang.String.replace(Unknown Source) ~[?:1.8.0_144]
	at me.glaremasters.guilds.commands.CommandList.getSkullsPage(CommandList.java:91) ~[?:?]
	at me.glaremasters.guilds.commands.CommandList.execute(CommandList.java:135) ~[?:?]
	at me.glaremasters.guilds.commands.base.CommandHandler.onCommand(CommandHandler.java:81) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.1.jar:git-Paper-1190]
	... 15 more

```

**Comment by darbyjack** [comment]
Is your server cracked? There should never be an issue  obtaining a player's UUID.

**Comment by mibby** [comment]
My server is not cracked. I'm assuming the errors occur because my local test server does not contain a usercache.json of the users part of a guild on my main server. So when trying to display users on the local server, it doesn't know who the UUID belongs to, nor does Guilds obtain the playername based on the UUID if it doesn't exist.

**Comment by darbyjack** [comment]
I don't see any way for the UUIDs to get messed up on my end for this, so I will close this, I've tested a few different thing that hasn't "corrupted" the Guilds.json file, if you can tell me how to replicate, I'll re-open this.

**Comment by mibby** [comment]
Try reproducing it by grabbing a copy of the guild I pasted here https://github.com/darbyjack/Guilds-Plugin/issues/46. Simply add that guild to your guild json file, then try ```/guild admin info Aurora``` and ```/guilds list```.
