### ISSUE TITLE
version 1.7.10 kc server Can not load

### ISSUE THREAD

**Issue by Xiazihong** [darbyjack/Guilds-Plugin#59]
If you do not understand what I am saying Please use this translation  (https://translate.google.com/)

[20:03:41] [Server thread/INFO]: [Guilds] Enabling Guilds v1.8.6-RELEASE
[20:03:41] [Server thread/ERROR]: Error occurred while enabling Guilds v1.8.6-RELEASE (Is it up to date?)
java.lang.NoClassDefFoundError: me/glaremasters/guilds/database/databases/json/Json$1
	at me.glaremasters.guilds.database.databases.json.Json.initialize(Json.java:43) ~[?:?]
	at me.glaremasters.guilds.Main.setDatabaseType(Main.java:389) ~[?:?]
	at me.glaremasters.guilds.Main.onEnable(Main.java:132) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:507) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:481) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:441) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:353) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.ClassNotFoundException: Failed to remap class me.glaremasters.guilds.database.databases.json.Json$1
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:493) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:414) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	... 14 more
Caused by: java.lang.NoClassDefFoundError: guava10/com/google/common/reflect/TypeToken
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_102]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:481) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:414) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:211) ~[PluginClassLoader.class:1.7.10-R0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	... 14 more`

**Comment by darbyjack** [comment]
It states on the website that the plugin doesn't support kc.
