### ISSUE TITLE
NullPointerException on guilds list.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#67]
Guilds dev 176

```
[13:48:54] [Server thread/INFO]: player issued server command: /guild list
[13:48:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'guild' in plugin Guilds v1.9.0-BETA
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1230]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1459) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1264) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1230]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1230]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1230]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at me.glaremasters.guilds.commands.CommandList.getSkullsPage(CommandList.java:66) ~[?:?]
	at me.glaremasters.guilds.commands.CommandList.execute(CommandList.java:156) ~[?:?]
	at me.glaremasters.guilds.commands.base.CommandHandler.onCommand(CommandHandler.java:84) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1230]
	... 15 more
```

**Comment by mibby** [comment]
@darbyjack Dev 169 (Guilds-1.8.9-RELEASE) seems to have problems. Downgrading to dev 162 (Guilds-1.8.8-RELEASE) seems to fix all my issues, at least at first glance. So I think the syncing issue, despite being disabled, may be causing the list exception, as well as guild reset problem.

**Comment by darbyjack** [comment]
Haven't been able to replicate
