### ISSUE TITLE
NullPointerException on guild ally.

### ISSUE THREAD

**Issue by mibby** [darbyjack/Guilds-Plugin#70]
Guilds dev 178

```
[09:17:40] [Server thread/INFO]: player issued server command: /guild ally add VilleDuFleur
[09:17:40] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'guild' in plugin Guilds v1.9.0-BETA
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1244]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:676) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1466) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1271) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1244]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1244]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1244]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NullPointerException
	at me.glaremasters.guilds.message.Message.sendMessage(Message.java:71) ~[Guilds-1.9.0-BETA-all.jar:?]
	at me.glaremasters.guilds.commands.CommandAlly.lambda$execute$7(CommandAlly.java:106) ~[Guilds-1.9.0-BETA-all.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_152]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_152]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_152]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_152]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_152]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_152]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_152]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_152]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_152]
	at me.glaremasters.guilds.commands.CommandAlly.execute(CommandAlly.java:105) ~[Guilds-1.9.0-BETA-all.jar:?]
	at me.glaremasters.guilds.commands.base.CommandHandler.onCommand(CommandHandler.java:84) ~[Guilds-1.9.0-BETA-all.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1244]
	... 15 more
```

**Comment by darbyjack** [comment]
Is your server cracked?

**Comment by mibby** [comment]
No. The server is offline connected with an online BungeeCord.

**Comment by darbyjack** [comment]
Fixed
