### ISSUE TITLE
seems mysql not support utf-8 encode

### ISSUE THREAD

**Issue by tianji1993** [darbyjack/Guilds-Plugin#72]
version: 19
mysql works well, and the default encode for database is utf-8.
### Steps to reproduce the problem
1. enable MySQL support by edit file "/plugins/Guilds/config.yml" , tables automatically created;
2. in game type in command "/guild create 露希卡" and "/guild confirm", shows create success;
3. in MySQL table view, open table "guilds", see there have a record which have name = **"???"**

maybe we can add force encode special in database field by adding:
"?useUnicode=true&characterEncoding=UTF-8"

**Comment by tianji1993** [comment]
after adding "?useUnicode=true&characterEncoding=UTF-8" into database field at config.yml it seems works, but I get following error after every "/guild reload", but seems data is saved into database. can this be repaired? Thanks!

```
[14:04:15] [TaskChainAsyncQueue Thread 29/ERROR]: [Guilds] An error occurred while adding a member with an UUID of '9828d7ec-2eb9-4a1e-bf64-7c1e4396b4b3' to guild '露希卡'
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: java.sql.SQLException: Invalid utf8 character string: 'ACED00'
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.execute(MySql.java:301)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$updateGuild$24(MySql.java:202)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1074)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.execute0(TaskChain.java:1021)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.execute(TaskChain.java:990)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.execute(TaskChain.java:976)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.updateGuild(MySql.java:221)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.guild.Guild.updateGuild(Guild.java:366)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.guild.Guild.addMember(Guild.java:177)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$getGuilds$19(MySql.java:155)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1074)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1248)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1071)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1248)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1078)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: java.sql.SQLException: Invalid utf8 character string: 'ACED00'
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2487)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.execute(MySql.java:301)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$updateGuild$24(MySql.java:202)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1074)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.execute0(TaskChain.java:1021)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.execute(TaskChain.java:990)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.execute(TaskChain.java:976)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.updateGuild(MySql.java:221)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.guild.Guild.updateGuild(Guild.java:366)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.guild.Guild.addMember(Guild.java:177)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$getGuilds$19(MySql.java:155)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1074)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1248)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1071)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1248)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1203)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1157)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at co.aikar.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1078)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:04:15] [TaskChainAsyncQueue Thread 29/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:04:15] [Server thread/INFO]: [Guilds] Tables 'guilds', 'members', 'guild_homes', 'guild_allies', and 'invited_members' created!

```

**Comment by darbyjack** [comment]
What do you mean after you added that into the config.yml?

**Comment by tianji1993** [comment]
sorry for my bad english, here is the config field:
```
 ......
 # Note: Database needs to be created manually
  database: "guilds?useUnicode=true&characterEncoding=UTF-8"
  pool-size: 10
 ......
```

after setting to above, the MySQL database seems worked , but I still get an error while I type in "/guild reload".

**Comment by sumdream** [comment]
The same problem to me!I am using MariaDB .

**Comment by sumdream** [comment]
`[22:00:03 ERROR]: [Guilds] An error occurred while adding a member with an UUID of 'c13b83e1-d55d-3cd4
-a374-f7c1bf71eaa7' to guild 'Crazy'
[22:00:03 WARN]: java.sql.SQLException: Invalid utf8 character string: 'ACED00'
[22:00:03 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[22:00:03 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[22:00:03 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:185
8)
[22:00:03 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[22:00:03 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatemen
t.java:44)
[22:00:03 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPrep
aredStatement.java)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.execute(MySql.java:28
1)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$updateGuild$24
(MySql.java:200)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1102)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.execute0(TaskChain.java:1049)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.execute(TaskChain.java:1018)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.execute(TaskChain.java:1004)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.updateGuild(MySql.jav
a:220)
[22:00:03 WARN]:        at me.glaremasters.guilds.guild.Guild.updateGuild(Guild.java:366)
[22:00:03 WARN]:        at me.glaremasters.guilds.guild.Guild.addMember(Guild.java:179)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$getGuilds$19(M
ySql.java:153)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1102)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1276)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1099)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1276)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1106)
[22:00:03 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:00:03 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[22:00:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:00:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:00:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:00:03 WARN]: java.sql.SQLException: Invalid utf8 character string: 'ACED00'
[22:00:03 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[22:00:03 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[22:00:03 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
[22:00:03 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:185
8)
[22:00:03 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
[22:00:03 WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatemen
t.java:44)
[22:00:03 WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPrep
aredStatement.java)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.execute(MySql.java:28
1)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$updateGuild$24
(MySql.java:200)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1102)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.execute0(TaskChain.java:1049)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.execute(TaskChain.java:1018)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.execute(TaskChain.java:1004)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.updateGuild(MySql.jav
a:220)
[22:00:03 WARN]:        at me.glaremasters.guilds.guild.Guild.updateGuild(Guild.java:366)
[22:00:03 WARN]:        at me.glaremasters.guilds.guild.Guild.addMember(Guild.java:179)
[22:00:03 WARN]:        at me.glaremasters.guilds.database.databases.mysql.MySql.lambda$getGuilds$19(M
ySql.java:153)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1102)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1276)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.nextTask(TaskChain.java:1099)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.access$1000(TaskChain.java:56)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1276)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1231)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1185)
[22:00:03 WARN]:        at co.aikar.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1106)
[22:00:03 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:00:03 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[22:00:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:00:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:00:03 WARN]:        at java.lang.Thread.run(Unknown Source)`
